"""add root_cause table

Revision ID: 070624270a2e
Revises: 586a57ddc665
Create Date: 2018-12-14 17:12:59.579515

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '070624270a2e'
down_revision = '586a57ddc665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('root_cause',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('user')
    op.add_column('bug', sa.Column('root_cause_id', sa.Integer(), nullable=False))
    op.alter_column('bug', 'bug_tracker_url',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.create_index(op.f('ix_bug_root_cause_id'), 'bug', ['root_cause_id'], unique=False)
    op.create_unique_constraint(None, 'bug', ['bug_tracker_url'])
    op.create_foreign_key(None, 'bug', 'root_cause', ['root_cause_id'], ['id'])
    op.drop_column('bug', 'root_cause')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bug', sa.Column('root_cause', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bug', type_='foreignkey')
    op.drop_constraint(None, 'bug', type_='unique')
    op.drop_index(op.f('ix_bug_root_cause_id'), table_name='bug')
    op.alter_column('bug', 'bug_tracker_url',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.drop_column('bug', 'root_cause_id')
    op.create_table('user',
                    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('username', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
                    sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=False),
                    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
                    sa.Column('info', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
                    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
                    sa.Column('sid', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('user_id', name='user_pkey'),
                    sa.UniqueConstraint('email', name='user_email_key')
                    )
    op.drop_table('root_cause')
    # ### end Alembic commands ###
