0_scrapy_at_a_glance_quotes_to_scrape:
	scrapy runspider my_project/spiders/0_scrapy_at_a_glance_quotes_to_scrape.py \
		-o results/0_scrapy_at_a_glance_quotes_to_scrape.jsonl

start_splash:
	docker run -p 8050:8050 scrapinghub/splash

stackoverflow:
	scrapy crawl stack -o stackoverflow.json -t json

facebook-selenium:
	scrapy crawl facebook-selenium-spider -o facebook-selenium.json -t json

loza:
	scrapy crawl loza -o loza.json -t json

test:
	scrapy crawl test